---
- name: Create folders
  shell:
    cmd: "mkdir -p {{ inception_dir }} && mkdir -p {{ db_dir }} && mkdir -p {{ wp_dir }}"

- name: Copy all inception files
  copy:
    src: "./"
    dest: "{{ inception_dir }}"
    mode: "0744"

- name: Copy docker-compose.yml template
  template:
    src: templates/docker-compose.yml.j2
    dest: "{{ inception_dir }}/docker-compose.yml"

# - name: Run docker-compose
#   shell:
#     cmd: "cd {{ inception_dir }} && docker-compose up -d"