# server {
# 	listen 9090 default_server;
# 	listen [::]:80 default_server;


# 	root /var/www/html/phpmyadmin;

# 	index index.php index.html index.htm index.nginx-debian.html;

# 	server_name _;

# 	location / {
# 		# First attempt to serve request as file, then
# 		# as directory, then fall back to displaying a 404.
# 		try_files $uri $uri/ =404;
# 		proxy_redirect     off;
# 		proxy_set_header X-Forwarded-Proto $scheme;
# 		proxy_set_header X-Real-IP $remote_addr;
# 		proxy_set_header X-Forwarded-For $remote_addr;
# 		proxy_set_header Host $host;
# 	}

# 	# pass PHP scripts to FastCGI server
# 	#
# 	location ~ \.php$ {
# 		fastcgi_index index.php;


# 	# 	include snippets/fastcgi-php.conf;

# 	# 	# With php-fpm (or other unix sockets):
# 	# 	fastcgi_pass unix:/run/php/php7.3-fpm.sock;
# 	# 	# With php-cgi (or other tcp sockets):
# 	# #	fastcgi_pass 127.0.0.1:9090;
# 	}
# }

worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;

    keepalive_timeout 65;

    server {
        listen 80;
        server_name localhost;  # You might want to change this to your domain or IP

        root /var/www/html/phpmyadmin;

        index index.php index.html index.htm;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass 127.0.0.1:9000;  # Assuming PHP-FPM is listening on port 9000
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $uri;
        }
    }
}